// Copyright 2026 DegradingAnt. Licensed under GPL-3.0.

#pragma once

#include "CoreMinimal.h"

/**
 * THE MASTER ON/OFF SWITCH — and OFF has to mean RELEASED, not merely "stopped writing".
 *
 * P4.2 (`_DESIGN-R2-2026-08-09.md` §PHASE 4). Ships as a console variable rather than a settings row,
 * on purpose: `UFGUserSetting` assets are editor work and do not exist yet, and building the whole
 * consumption layer before any row exists is unwired infrastructure — the old mod's single most
 * repeated fault. The row, when it arrives, drives this cvar. The cvar has a consumer today.
 *
 * ★ WHY "OFF" IS THE HARD HALF.
 *
 * Stopping FPM from writing more console variables is trivial and WRONG. Every value FPM has already
 * pushed stays applied, so a user who turns the mod off still has FPM's settings on their machine — and
 * `.uplugin` says, in the Description a player reads on ficsit.app, that it *"leaves nothing behind"*.
 * So OFF routes through `FPMCVarWriter::ReleaseAll`, which restores each cvar's prior value AND prior
 * SetBy priority, and which already proves that path on its own probe cvar at every boot.
 *
 * ⚠ AND OFF WAS A LIE UNTIL 0.11.9. `FPMFixes::DisarmAll()` walks the armed list calling `Disarm()`,
 * but `IFPMFix::Disarm()` defaults to `{}` and 13 fixes that installed hooks never overrode it. This
 * switch could not have shipped before that was repaired: it would have reported FPM disabled while
 * seventeen hooks stayed installed, and the fix inventory would have read zero armed — the inventory
 * lying being the one thing `FPMHookLedger` exists to prevent.
 *
 * ★ IT IS REVERSIBLE, and that needed a registry change. `DisarmAll` empties the armed list, and the
 * arm sequence lives in `StartupModule`, so without `FPMFixes::RearmAll()` an OFF would have been
 * permanent for the session.
 *
 * ⚠ WHAT ON DOES NOT RESTORE, stated because a half-true report is worse than none: a fix whose real
 * work happens in `OnWorldLoad` comes back ARMED BUT INERT until the next world load. Re-arming does
 * not replay one. Both the log line and `FPM.Enabled`'s help text say so.
 */
namespace FPMMasterSwitch
{
	/**
	 * Registers the master cvar sink AND one `FPM.Fix.<Name>` toggle per registered fix (P4.3).
	 *
	 * Call once from `StartupModule`, AFTER every fix has armed — the per-fix cvars are generated by
	 * ENUMERATING the registry, so anything armed later would silently have no toggle.
	 */
	FICSITSPERFORMANCEMANAGER_API void Install();

	/** True when FPM is currently enabled. Reads the live cvar, not a cached copy. */
	FICSITSPERFORMANCEMANAGER_API bool IsEnabled();
}

/**
 * P4.3 — one console variable per fix, GENERATED FROM THE REGISTRY.
 *
 * ★ NO HAND-WRITTEN LIST, and that is the whole point. Every fix already declares `IFPMFix::Name()`, so
 * the toggles enumerate `FPMFixes::Registered()` instead of naming anything twice. A second declaration
 * site is a bug by construction and this project has already paid for one — `MenuInjector` was `true`
 * in a header and `false` in a config, and the config won.
 *
 * ⚠ THE CVAR NAME IS DERIVED, NOT THE FIX NAME VERBATIM. Fix names are hyphenated (`static-base`,
 * `hologram-net`) and no engine console variable uses a hyphen, so relying on the parser tolerating one
 * is a guess. Hyphens are removed and the following letter capitalised: `static-base` becomes
 * `FPM.Fix.StaticBase`. `FPM.Fix.List` prints both names side by side so the mapping is never inferred.
 *
 * ⚠ THE MASTER SWITCH WINS. With `FPM.Enabled 0`, setting a per-fix toggle to 1 is REFUSED and says so.
 * Silently arming one fix inside a mod the user has turned off is the kind of interaction that makes a
 * settings surface untrustworthy.
 */
namespace FPMFixToggles
{
	/** `FPM.Fix.<Name>` for every registered fix, plus `FPM.Fix.List`. Called by `Install()`. */
	void Install();

	/** Re-reads every toggle and applies it. Used after the master switch turns back ON. */
	void ReapplyAll();
}
