// Copyright 2026 DegradingAnt. Licensed under GPL-3.0.

#pragma once

#include "CoreMinimal.h"
#include "Templates/Function.h"

/**
 * THE MASTER ON/OFF SWITCH — and OFF has to mean RELEASED, not merely "stopped writing".
 *
 * P4.2 (`_DESIGN-R2-2026-08-09.md` §PHASE 4). Ships as a console variable rather than a settings row,
 * on purpose: `UFGUserSetting` assets are editor work and do not exist yet, and building the whole
 * consumption layer before any row exists is unwired infrastructure — the old mod's single most
 * repeated fault. The row, when it arrives, drives this cvar. The cvar has a consumer today.
 *
 * ★ WHY "OFF" IS THE HARD HALF.
 *
 * Stopping FPM from writing more console variables is trivial and WRONG. Every value FPM has already
 * pushed stays applied, so a user who turns the mod off still has FPM's settings on their machine — and
 * `.uplugin` says, in the Description a player reads on ficsit.app, that it *"leaves nothing behind"*.
 * So OFF routes through `FPMCVarWriter::ReleaseAll`, which restores each cvar's prior value AND prior
 * SetBy priority, and which already proves that path on its own probe cvar at every boot.
 *
 * ⚠ AND OFF WAS A LIE UNTIL 0.11.9. `FPMFixes::DisarmAll()` walks the armed list calling `Disarm()`,
 * but `IFPMFix::Disarm()` defaults to `{}` and 13 fixes that installed hooks never overrode it. This
 * switch could not have shipped before that was repaired: it would have reported FPM disabled while
 * seventeen hooks stayed installed, and the fix inventory would have read zero armed — the inventory
 * lying being the one thing `FPMHookLedger` exists to prevent.
 *
 * ★ IT IS REVERSIBLE, and that needed a registry change. `DisarmAll` empties the armed list and the
 * arm sequence lives in `StartupModule`, so without a second route back an OFF would have been
 * permanent for the session. That route is `FPMFixToggles::ReapplyAll()`, which arms each registered
 * fix to what its own toggle asks for. It was `FPMFixes::RearmAll()` until 2026-08-15; that armed
 * everything unconditionally and had to be undone by the toggles a moment later, and the undoing left
 * unowned rows in `FPMHookLedger` for the rest of the session.
 *
 * ⚠ WHAT ON DOES NOT RESTORE, stated because a half-true report is worse than none: a fix whose real
 * work happens in `OnWorldLoad` comes back ARMED BUT INERT until the next world load. Re-arming does
 * not replay one. Both the log line and `FPM.Enabled`'s help text say so.
 */
namespace FPMMasterSwitch
{
	/**
	 * Registers the master cvar sink AND one `FPM.Fix.<Name>` toggle per registered fix (P4.3).
	 *
	 * Call once from `StartupModule`, AFTER every fix has armed — the per-fix cvars are generated by
	 * ENUMERATING the registry, so anything armed later would silently have no toggle.
	 */
	FICSITSPERFORMANCEMANAGER_API void Install();

	/** True when FPM is currently enabled. Reads the live cvar, not a cached copy. */
	FICSITSPERFORMANCEMANAGER_API bool IsEnabled();

	/**
	 * Register a callback to run when the switch goes OFF, BEFORE FPMFixes::DisarmAll() and
	 * FPMCVarWriter::ReleaseAll(). Item 2: FPM.Bisect / FPM.Prove write outside the writer's tagged
	 * 0x07 hold (the accepted ECVF_SetByConsole exception, FPMCVarProbe.cpp:1-21), so ReleaseAll's
	 * tag-based Unset cannot reach an active run. "FPM.Off releases everything including an active
	 * Bisect" is the DONE condition this exists to satisfy.
	 *
	 * Call from a file-scope static initializer in the OWNING translation unit (see FPMCVarProbe.cpp)
	 * so the hook exists before StartupModule can ever reach the OFF branch.
	 */
	FICSITSPERFORMANCEMANAGER_API void RegisterStopHook(TFunction<void()> Hook);
}

/**
 * P4.3 — one console variable per fix, GENERATED FROM THE REGISTRY.
 *
 * ★ NO HAND-WRITTEN LIST, and that is the whole point. Every fix already declares `IFPMFix::Name()`, so
 * the toggles enumerate `FPMFixes::Registered()` instead of naming anything twice. A second declaration
 * site is a bug by construction and this project has already paid for one — `MenuInjector` was `true`
 * in a header and `false` in a config, and the config won.
 *
 * ⚠ THE CVAR NAME IS DERIVED, NOT THE FIX NAME VERBATIM. Fix names are hyphenated (`static-base`,
 * `hologram-net`) and no engine console variable uses a hyphen, so relying on the parser tolerating one
 * is a guess. Hyphens are removed and the following letter capitalised: `static-base` becomes
 * `FPM.Fix.StaticBase`. `FPM.Fix.List` prints both names side by side so the mapping is never inferred.
 *
 * ⚠ THE MASTER SWITCH WINS. With `FPM.Enabled 0`, setting a per-fix toggle to 1 is REFUSED and says so.
 * Silently arming one fix inside a mod the user has turned off is the kind of interaction that makes a
 * settings surface untrustworthy.
 */
namespace FPMFixToggles
{
	/** `FPM.Fix.<Name>` for every registered fix, plus `FPM.Fix.List`. Called by `Install()`. */
	void Install();

	/**
	 * Re-reads every toggle and applies it, arming and disarming to match. This is the ONLY thing the
	 * master switch's ON path calls.
	 *
	 * ★ IT IS THE WHOLE RE-ARM, NOT A CORRECTION APPLIED AFTER ONE. The ON path used to call
	 * `FPMFixes::RearmAll()` first, which armed every registered fix including the `DefaultArmed() ==
	 * false` ones, and this function then disarmed them again. That round trip installed and removed
	 * real funchook detours and left permanently unowned rows in `FPMHookLedger`. See the comment at
	 * the call site for the measurement.
	 *
	 * A registered fix with no toggle (its cvar failed to register) falls back to `DefaultArmed()`,
	 * which is what `RearmAll` used to give it.
	 */
	void ReapplyAll();
}
