// Copyright 2026 DegradingAnt. Licensed under GPL-3.0.

#pragma once

#include "CoreMinimal.h"
#include "Core/FPMFixContract.h"

#include <atomic>

class AFGBlueprintSubsystem;

/**
 * BLUEPRINT SWEEP GATE — stop re-answering a question whose inputs have not changed.
 *
 * ★ THE COST, from the vanilla headers rather than from reputation. `AFGBlueprintSubsystem::Tick`
 * (`FGBlueprintSubsystem.h:180`) accumulates `mTimeSinceLastRecipeCheck` (`:691`) and, roughly every two
 * seconds, calls `RefreshBlueprintRecipeRequirements()` (`:201`) — whose own doc comment says it
 * *"Iterates all existing blueprint descriptors and sets whether they meet the recipe requirements"*.
 * That is O(library) on the GAME THREAD, forever, at a fixed cadence. Ant's library is 262 blueprints.
 *
 * ★ WHY THE OBVIOUS FIX IS THE WRONG ONE, and this is the whole reason this file exists. A community mod
 * ("Blueprint Stutter Fix") removes the stutter by DISABLING the loop, and its own page states the
 * price: imported blueprints *"might not show up at first, but saving and reloading should fix it"*.
 * Ant hit exactly that on 2026-08-10 — *"blueprints didnt update when playing, only a relog of the client
 * fixed the blueprint cost bug"*. Trading correctness for frame time is not a performance fix, it is a
 * different bug with better framing.
 *
 * ★ ANT'S DESIGN, WHICH IS BETTER THAN THE ONE I PROPOSED FIRST. She asked: *"can we force an update when
 * the game wants to and keep the loop otherwise?"* My first answer was to AMORTISE — check a slice of the
 * library per call. That still pays a cost every two seconds and still accepts bounded staleness. Hers
 * pays NOTHING in the steady state and has NO staleness, because it rests on an observation about the
 * inputs rather than on spreading the work out:
 *
 *   `AreRecipeRequirementsMetForBlueprint(header)` (`:337`) is a pure function of exactly two things.
 *   `FBlueprintHeader` carries `Cost`, `Recipes` and `RecipeRefs`, so the answer can only move when
 *     1. a recipe becomes AVAILABLE, or
 *     2. the blueprint set itself changes (import, delete, re-save).
 *   Watch both, and every sweep in between is provably incapable of changing a single answer.
 *
 * So the loop is kept, every sweep the game actually wants runs UNTOUCHED, and only the provably-inert
 * ones are cancelled. Both signals are reachable:
 *   - `AFGRecipeManager::mOnRecipeAvailable` (`FGRecipeManager.h:151`, `FFGOnRecipeAvailableDelegate`
 *     declared `:17`) — this IS the game saying "something changed".
 *   - `AFGBlueprintSubsystem::mBlueprintDescriptorsRequireRefresh` (`:697`) — vanilla's own dirty flag,
 *     set by the public `MarkBlueprintDescriptorsForRefresh()` (`:213`). Private, hence the friend entry
 *     in `Config/AccessTransformers.ini`.
 *
 * ⚠⚠ THE ASSUMPTION THIS RESTS ON IS NOT PROVEN, AND SO IT SHIPS WITH ITS OWN PROOF.
 *
 * `FGBlueprintSubsystem.cpp` in the SML tree is an autogenerated stub, so the BODY of
 * `AreRecipeRequirementsMetForBlueprint` is only in the retail binary. The name, and the separate
 * `mIgnoreRecipeRequirements` list (`:645`), both point to "are these recipes unlocked" — but if it also
 * consults player INVENTORY ("can I afford it right now"), then inventory changes are a third input, our
 * trigger set is incomplete, and this fix becomes a rarer, harder-to-notice version of the bug it
 * replaces. That is precisely the failure this project keeps paying for.
 *
 * So the gate AUDITS ITSELF. On a timer it recomputes the answer for every descriptor using the public
 * `AreRecipeRequirementsMetForBlueprint` and compares it against the cached
 * `GetRecipeRequirementsAreMet()`. If a cancelled sweep would EVER have changed an answer, that is a
 * disagreement, and it is logged as a WARNING naming the blueprint. The fix does not go quietly stale;
 * it tells you its model of the world is wrong. Same discipline as `FPMCVarWriter` proving its release
 * path every boot rather than asserting it works.
 *
 * ★ AND THE AUDIT IS ALSO THE LIVENESS PROOF. Ask of every counter here: what input makes it non-zero?
 * `SweepsCancelled` moves on the first inert sweep, `SweepsAllowed` on the first real change, and
 * `AuditDisagreements` on the first hole in the model. None of them can be structurally stuck at zero.
 *
 * FALLS THROUGH BY DEFAULT. Anything unexpected — no subsystem, no recipe manager, an empty library,
 * the audit disagreeing — resolves to LETTING VANILLA RUN. A guard that fails open toward the original
 * behaviour cannot be the reason a blueprint goes missing.
 */
class FICSITSPERFORMANCEMANAGER_API FFPMBlueprintSweepGate final : public IFPMFix
{
public:
	static FFPMBlueprintSweepGate& Get();

	virtual const TCHAR* Name() const override { return TEXT("blueprint-sweep-gate"); }

	/**
	 * ⚠ Client-side. `AFGBlueprintSubsystem` exists on a dedicated server, but the blueprint LIBRARY is a
	 * per-player collection of local files and the recipe-requirement flag drives the build-menu UI,
	 * which a server does not draw. Decided from the header rather than assumed: the descriptors are
	 * built by `RefreshBlueprintsAndDescriptors()` from files enumerated locally, and
	 * `GenerateManifest()`'s comment says *"Clients evaluate their checksums at startup"*.
	 * ★ IF A SERVER BOOT SHOWS THIS SWEEP RUNNING THERE TOO, widen it — but do that on evidence.
	 */
	virtual EFPMFixSide Side() const override { return EFPMFixSide::NeverOnDedicatedServer; }

	/**
	 * OriginNamed. The cause is not a guess and not a choke point: a fixed-cadence full re-verification
	 * whose inputs change rarely. We are removing the waste, not routing around a symptom, and the
	 * blueprints stay correct — which is the whole distinction this enum exists to protect.
	 */
	virtual EFPMOriginStatus OriginStatus() const override { return EFPMOriginStatus::OriginNamed; }

	virtual FPMDiag::EChannel Channel() const override { return FPMDiag::EChannel::BlueprintSweep; }

	virtual void Arm() override;
	virtual void Disarm() override;
	virtual void OnWorldLoad(UWorld* World) override;

	/** `FPM.Blueprint.Report` — cancelled vs allowed, and whether the audit has ever disagreed. */
	void LogReport();

	/** `FPM.Blueprint.Audit` — run the correctness audit right now instead of waiting for the timer. */
	void RunAuditNow();

private:
	/** The gate itself. Returns true when the sweep should be CANCELLED. */
	bool ShouldCancelSweep(AFGBlueprintSubsystem* Subsystem);

	/** Recompute every answer and compare against the cache. Returns the number of disagreements. */
	int32 AuditAgainstCache(AFGBlueprintSubsystem* Subsystem, bool bLogEach);

	/** Late-bound: the recipe manager is an actor and does not exist until a world does. */
	void BindRecipeManager(UWorld* World);

	FDelegateHandle SweepHookHandle;
	TWeakObjectPtr<class AFGRecipeManager> BoundRecipeManager;

	/** Forces the next sweep to be a real one. Set on world load and whenever the model is unsure. */
	std::atomic<bool> bDirty{true};   // starts dirty: the first sweep after load must always run

	double LastAuditSeconds = 0.0;

	/**
	 * When the last sweep was ALLOWED through. LogReport prints its age — a 95% cancel rate reads the
	 * same whether the last real sweep was four seconds or forty minutes ago, and only the second says
	 * the library has genuinely gone quiet. Zero means none has been allowed yet, which the report
	 * states in words rather than printing as "0.0 s ago".
	 */
	double LastAllowedSweepSeconds = 0.0;

	/**
	 * ⚠ THE RECIPE SIGNAL IS A COUNT, NOT A DELEGATE, and that downgrade is named here rather than
	 * discovered later.
	 *
	 * `FFGOnRecipeAvailableDelegate` (`FGRecipeManager.h:17`, member `:151`) is a DYNAMIC multicast, so
	 * binding it needs a `UFUNCTION` on a `UObject`. This fix is a plain C++ class and has neither, and a
	 * `UObject` shim whose only job is to receive one event is more surface than the problem deserves.
	 * So the gate reads `AFGRecipeManager::GetAllAvailableRecipes()` — the const-reference overload at
	 * `:69`, which hands back `mAvailableRecipes` directly and allocates nothing — once per sweep, and
	 * compares the length.
	 *
	 * A count cannot see a simultaneous add and remove. Recipes are not removed in normal play, so it
	 * holds here — but that is an assumption about the GAME, not a property of the code, and it is
	 * exactly what the audit exists to catch being wrong.
	 *
	 * Starts at -1 so the first sweep always reads as changed.
	 */
	int32 LastAvailableRecipes = -1;

	int32 SweepsCancelled = 0;
	int32 SweepsAllowed = 0;
	int32 AuditsRun = 0;
	int32 AuditDisagreements = 0;
	int32 LastLibrarySize = 0;
};
