// Copyright 2026 DegradingAnt. Licensed under GPL-3.0.

#pragma once

#include "CoreMinimal.h"

#include "Core/FPMFixContract.h"

/**
 * WIRE NULL GUARD — sweep null entries out of power-wire arrays BEFORE the autosave walks them.
 *
 * ★ THIS ONE KILLED THE DEDICATED SERVER, and the crash is on record rather than inferred. 2026-08-09,
 * 21:42:41 local, mid-session with two players connected:
 *
 *     LogCore: === Critical error: ===
 *     Unhandled Exception: SIGSEGV: unaligned memory access at address 0x0000000000000000
 *       UClass::ImplementsInterface(UClass const*) const          Class.cpp:6167
 *       FFastSaveReferenceCollector::HandleObjectReference        FGSaveSession.cpp:2577
 *       FFastSaveReferenceCollector::GenerateSaveObjects          FGSaveSession.cpp:2632
 *       UFGSaveSession::SaveLevelState                            FGSaveSession.cpp:1717
 *       UFGSaveSession::SaveWorldImplementation                   FGSaveSession.cpp:1788
 *       UFGSaveSession::SaveWorldEndOfFrame                       FGSaveSession.cpp:2165
 *       UWorld::Tick -> UFGGameEngine::Tick -> FEngineLoop::Tick
 *
 * The autosave walks every saved object's property graph. One reference in that graph had a null
 * UClass, and `ImplementsInterface` dereferenced it. The server died; Ant and SunFry were frozen for
 * 26 seconds (the client logged `CreateSavedMove: Hit limit of 96 saved moves` nine times, 2 s after
 * the server went down) and quit. Autosaves had been failing before anyone noticed, which is the part
 * that makes this a data-loss bug and not just a crash.
 *
 * ★ WHERE THE NULLS COME FROM, and why the guard is worth having even once that is fixed. Two minutes
 * before the crash the server logged, 108 times in two bursts:
 *     LogSave: Warning: found 2 nullpointers in mWires during load
 * `mWires` is `TArray<TObjectPtr<AFGBuildableWire>>` on `UFGCircuitConnectionComponent`
 * (FGCircuitConnectionComponent.h:184). Preceding those, 3,242 times server-side and 2,549 client-side:
 *     LogSave: Warning: Failed to find level NogsLevel
 * `NogsLevel` is Nogg-aholic's DEVELOPER TEST MAP (`/NogsLevel/NogsLevel.NogsLevel`, documented in the
 * ficsit modding docs' TestingResources page), which is not installed and never was. Something in the
 * world references it, the reference cannot resolve, and dangling entries land in wire arrays.
 *
 * ⚠ THAT LAST LINK IS A HYPOTHESIS AND IS LABELLED ONE. Unresolvable-level -> null-wire is not proven,
 * only strongly co-located. THE GUARD DOES NOT DEPEND ON IT: a null in `mWires` is invalid state
 * however it got there, and walking it is what crashes. Fixing the source removes the cause; this
 * removes the crash. They are different jobs and both are worth doing.
 *
 * ★ WHY SWEEP RATHER THAN HOOK THE COLLECTOR. `FFastSaveReferenceCollector::HandleObjectReference` is
 * the frame that actually faults, and hooking it was considered and REJECTED on three counts, all from
 * the real headers rather than taste:
 *   1. It is a plain `FReferenceCollector` subclass (SaveCollectorArchive.h:12), not a UObject — there
 *      is no CDO to hand `SUBSCRIBE_METHOD_VIRTUAL` as a sample, and the symbol taken from a virtual
 *      member is a vtable thunk rather than the implementation.
 *   2. `Private/SaveCollectorArchive.cpp` is one of the 842 autogenerated stubs (its bodies are empty),
 *      so there is nothing local to hook against.
 *   3. It is called ONCE PER REFERENCE across the entire save graph. Ant's standing rule — "a
 *      performance mod stalling frames is a bad one" — rules out putting a branch there.
 * The sweep runs once per world load instead, over components we can enumerate cheaply.
 *
 * VIEWER-PLUS-REPAIR, and the repair is deliberately the narrow half. It removes NULL ENTRIES from a
 * wire array and resyncs the count. It never destroys an `AFGBuildableWire`, never touches a player
 * character, never deletes an item, and never writes an ini — a null hole is not a player's property,
 * it is the absence of one. `FPM.WireGuard.Repair 0` turns the repair off and leaves the naming half
 * running, because the naming half is what identifies the culprit building.
 */
class FICSITSPERFORMANCEMANAGER_API FFPMWireNullGuard final : public IFPMFix
{
public:
	static FFPMWireNullGuard& Get();

	virtual const TCHAR* Name() const override { return TEXT("wire-null-guard"); }

	/**
	 * Any. The crash was measured on the dedicated server, but the CLIENT log carries the same 2,549
	 * failed level lookups, so the same invalid state exists on both and a client autosave walks it the
	 * same way. Guarding one side only would fix the machine that happened to crash first.
	 */
	virtual EFPMFixSide Side() const override { return EFPMFixSide::Any; }

	/**
	 * Guard: the choke point is named and reproduced from a real callstack, but the ORIGIN — what puts a
	 * null into the array — is still open. Calling this OriginNamed would overstate what is known.
	 */
	virtual EFPMOriginStatus OriginStatus() const override { return EFPMOriginStatus::Guard; }

	virtual FPMDiag::EChannel Channel() const override { return FPMDiag::EChannel::WireGuard; }

	virtual void Arm() override;

	/** The sweep point. A world load is when a save's dangling references become live objects. */
	virtual void OnWorldLoad(UWorld* World) override;

	/** Print the running totals. Bound to `FPM.WireGuard.Report`. */
	void LogSummary(const TCHAR* Reason) const;

	/**
	 * Sweep now, on the current world. Bound to `FPM.WireGuard.Sweep` so the state can be checked
	 * immediately after a suspicious event rather than only at the next load.
	 */
	void SweepWorld(UWorld* World);

private:
	/** Components inspected, across every sweep this session. The denominator; never reported without it. */
	int32 ComponentsScanned = 0;
	int32 ComponentsWithNulls = 0;
	int32 NullEntriesFound = 0;
	int32 NullEntriesRemoved = 0;
	int32 SweepsRun = 0;
};
