// Copyright 2026 DegradingAnt. Licensed under GPL-3.0.

#include "Fixes/Vanilla/FPMCloneSensor.h"

#include "FicsitsPerformanceManager.h"
#include "Core/FPMHookLedger.h"

#include "FGGameMode.h"
#include "FGPlayerState.h"
#include "Online/ClientIdentification.h"
#include "GameFramework/PlayerController.h"

FFPMCloneSensor& FFPMCloneSensor::Get()
{
	static FFPMCloneSensor Instance;
	return Instance;
}

void FFPMCloneSensor::Arm()
{
	AFGGameMode* Sample = GetMutableDefault<AFGGameMode>();

	/*
	 * BOTH HALVES ARE NEEDED. The candidate list only exists BEFORE vanilla consumes it, and the
	 * outcome only exists after. Neither half alone answers "did the right state lose, and by how
	 * much".
	 *
	 * The handlers are NAMED lambdas rather than inline arguments so their bodies never sit inside a
	 * function-like macro — see the comma warning on FPM_SUBSCRIBE_VIRTUAL. That is what lets the
	 * range-for below use an explicit type without breaking the preprocessor.
	 */
	auto OnBeforeMatch = [](auto& Scope, AFGGameMode* Self, APlayerController* PC)
	{
		if (!Self || !PC || !Self->HasAuthority()) { return; }

		const AFGPlayerState* JoinerState = Cast<AFGPlayerState>(PC->PlayerState);
		if (!JoinerState)
		{
			UE_LOG(LogFicsitsPerformanceManager, Warning,
				TEXT("[FPM] clone sensor: join by %s arrived with NO AFGPlayerState — vanilla is about "
				     "to match against nothing. That alone would explain a fresh state being minted."),
				*GetNameSafe(PC));
			return;
		}

		const FClientIdentityInfo& JoinerId = JoinerState->GetClientIdentity();

		FString Fallbacks;
		for (const FString& FallbackName : JoinerId.FallbackAccountNames)
		{
			Fallbacks += (Fallbacks.IsEmpty() ? TEXT("") : TEXT(", ")) + FallbackName;
		}

		UE_LOG(LogFicsitsPerformanceManager, Display,
			TEXT("[FPM] ---- clone sensor: JOIN by '%s' ----"), *JoinerState->GetPlayerName());
		UE_LOG(LogFicsitsPerformanceManager, Display,
			TEXT("[FPM]   joiner: state=%s  offlineId='%s'  onlineAccountIds=%d  fallbackNames=[%s]"),
			*GetNameSafe(JoinerState),
			*JoinerId.OfflineId, JoinerId.AccountIds.Num(),
			Fallbacks.IsEmpty() ? TEXT("none") : *Fallbacks);

		/*
		 * ⚠ WE DO NOT CALL CalcClientIdentityMatchQuality, AND THAT IS NOT A STYLE CHOICE.
		 *
		 * It is declared public and static at ClientIdentification.h:20 and it is NOT EXPORTED from the
		 * shipping FactoryGame binary. Calling it compiles clean and dies at link:
		 *     ld.lld: error: undefined symbol:
		 *       FClientIdentityInfo::CalcClientIdentityMatchQuality(FClientIdentityInfo const&, ...)
		 * Header presence proves a SIGNATURE, never a symbol. Most of FactoryGame's private sources are
		 * autogenerated stubs, so a public declaration with no shipped body is normal here.
		 *
		 * So this reconstructs the comparison from the raw fields, following the rule CSS documents in
		 * that same header at :16-18 — "When no online ids are available, the offline id is used.
		 * Otherwise, if one online id matches, the identities are considered to match."
		 *
		 * ⚠ THIS IS FPM'S RECONSTRUCTION, NOT VANILLA'S SCORE, and every line says so. It cannot be used
		 * to second-guess vanilla's verdict. What it is good for is the actual question: the raw
		 * identity fields on both sides, printed together, so a human can see WHICH field went missing.
		 */
		int32 Considered = 0;
		int32 PlausibleMatches = 0;

		for (APlayerState* Candidate : Self->InactivePlayerArray)
		{
			const AFGPlayerState* FGCandidate = Cast<AFGPlayerState>(Candidate);
			if (!FGCandidate) { continue; }

			++Considered;
			const FClientIdentityInfo& CandidateId = FGCandidate->GetClientIdentity();
			const FString CandidateName = FGCandidate->GetPlayerName();

			const bool bOfflineMatch = !JoinerId.OfflineId.IsEmpty()
			                         && JoinerId.OfflineId == CandidateId.OfflineId;

			int32 SharedOnlineIds = 0;
			for (const auto& JoinerPair : JoinerId.AccountIds)
			{
				if (const UE::Online::FAccountId* Found = CandidateId.AccountIds.Find(JoinerPair.Key))
				{
					if (*Found == JoinerPair.Value) { ++SharedOnlineIds; }
				}
			}

			// CSS's documented precedence: online ids decide when either side has any, offline id only
			// otherwise.
			const bool bWouldMatch = (JoinerId.AccountIds.Num() > 0 || CandidateId.AccountIds.Num() > 0)
			                       ? (SharedOnlineIds > 0)
			                       : bOfflineMatch;
			if (bWouldMatch) { ++PlausibleMatches; }

			/*
			 * THE OBJECT NAME TIES THIS LINE BACK TO THE SAVE BYTES. THE UID SETTLES A QUESTION THE
			 * NAME CANNOT.
			 *
			 * The 2026-08-08 boot printed 26 candidate lines carrying only 13 distinct NAMES, and
			 * InactivePlayerArray.Num() agreed at 26. That has two readings and the name cannot tell
			 * them apart: either the array holds each entry twice, or there are 26 distinct objects
			 * whose names collide because UObject names are unique per OUTER, not globally.
			 *
			 * GetUniqueID() is the engine's internal object index, so two live objects can never
			 * share one. Equal uid twice => a genuine duplicate ENTRY. Different uids => 26 real
			 * states and the name collision was the illusion.
			 */
			UE_LOG(LogFicsitsPerformanceManager, Display,
				TEXT("[FPM]   candidate: state=%s(uid %u)  name='%s'%s  ownsPawn=%s  offlineId='%s'(%s)  "
				     "onlineIds=%d shared=%d  -> reconstructed: %s"),
				*GetNameSafe(FGCandidate), FGCandidate->GetUniqueID(),
				CandidateName.IsEmpty() ? TEXT("(EMPTY)") : *CandidateName,
				CandidateName.IsEmpty() ? TEXT("  <-- DEGENERATE") : TEXT(""),
				FGCandidate->GetOwnedPawn() ? TEXT("yes") : TEXT("NO"),
				*CandidateId.OfflineId, bOfflineMatch ? TEXT("SAME") : TEXT("differs"),
				CandidateId.AccountIds.Num(), SharedOnlineIds,
				bWouldMatch ? TEXT("WOULD match") : TEXT("would NOT match"));
		}

		UE_LOG(LogFicsitsPerformanceManager, Display,
			TEXT("[FPM]   %d candidate state(s) examined, %d reconstructed as matching, %d total in the "
			     "inactive array."),
			Considered, PlausibleMatches, Self->InactivePlayerArray.Num());

		/*
		 * THE TWO TELLS, AND THEY POINT AT DIFFERENT CAUSES.
		 *
		 * MORE THAN ONE match is H1 — several states carry the same identity, so the matcher ties and
		 * picks arbitrarily. That is the acute failure the save already shows for SunFry, and the line
		 * below names which states are tied, which is the answer to "which one is real".
		 *
		 * ZERO matches with candidates present is the joiner's own identity FIELDS being empty, not the
		 * scorer failing.
		 */
		if (PlausibleMatches > 1)
		{
			UE_LOG(LogFicsitsPerformanceManager, Warning,
				TEXT("[FPM]   ⚠ %d candidate states match this joiner. Vanilla will pick ONE and the "
				     "choice is arbitrary. The states listed above as 'WOULD match' are the duplicates "
				     "— this is the identity-duplication failure, not an identity-loss one."),
				PlausibleMatches);
		}
		else if (PlausibleMatches == 0 && Considered > 0)
		{
			UE_LOG(LogFicsitsPerformanceManager, Warning,
				TEXT("[FPM]   ⚠ NOT ONE of %d candidate states matches this joiner on identity fields. "
				     "A new state is the inevitable result. Compare the joiner's offlineId/onlineIds "
				     "above against the candidates' — the field that went missing is the bug."),
				Considered);
		}

		// Deliberately NO Scope.Override and NO Scope.Cancel. Vanilla decides; we only watch.
	};

	auto OnAfterMatch = [](const bool& bClaimed, AFGGameMode* Self, APlayerController* PC)
	{
		// Signature is fixed by SML: the return arrives by CONST REFERENCE, not by value, and there is
		// no scope parameter on an _AFTER handler.
		if (!Self || !PC || !Self->HasAuthority()) { return; }

		const AFGPlayerState* Bound = Cast<AFGPlayerState>(PC->PlayerState);

		UE_LOG(LogFicsitsPerformanceManager, Display,
			TEXT("[FPM]   RESULT: vanilla %s. bound state=%s  name='%s'  ownsPawn=%s"),
			bClaimed ? TEXT("CLAIMED an existing state")
			         : TEXT("did NOT claim — a NEW state will be minted"),
			*GetNameSafe(Bound),
			(Bound && !Bound->GetPlayerName().IsEmpty()) ? *Bound->GetPlayerName() : TEXT("(EMPTY)"),
			(Bound && Bound->GetOwnedPawn()) ? TEXT("yes") : TEXT("NO"));
	};

	FPM_SUBSCRIBE_VIRTUAL("clone-sensor", AFGGameMode::FindInactivePlayer, Sample, OnBeforeMatch);
	FPM_SUBSCRIBE_VIRTUAL_AFTER("clone-sensor", AFGGameMode::FindInactivePlayer, Sample, OnAfterMatch);
}
