// Copyright 2026 DegradingAnt. Licensed under GPL-3.0.

#pragma once

#include "CoreMinimal.h"
#include "Core/FPMDiag.h"
#include "Core/FPMFixContract.h"

/**
 * ★ WHO CALLS SetMeshes TOO LATE? 431 REJECTED CALLS AND NO NAME ON ANY OF THEM.
 *
 * Measured in Ant's client log, 2026-08-10, 431 times in one session and arriving in bursts — three in
 * the same millisecond on the same frame:
 *
 *     LogGame: Warning: BP_MaterialEffect_Dismantle_C_2147445857::SetMeshes,
 *              This cannot be called after PreStarted.
 *
 * ══ WHY THIS IS A DEFECT AND NOT LOG NOISE ══
 *
 * Vanilla's own contract, `FGMaterialEffectComponent.h:66`:
 *
 *     /** Set the meshes to override material on, cannot be called after PreStarted. *\/
 *     UFUNCTION( BlueprintCallable )
 *     void SetMeshes( TArray< UMeshComponent* > meshes );
 *
 * The call is REJECTED, so the meshes are never set, so the dismantle effect runs against an empty set.
 * That is wasted work and a missing visual, not a cosmetic warning — which is why it falls under Ant's
 * standing rule: *"all errors and warnings need fixing at the source so we actually fix issues and not
 * just quiet logs."*
 *
 * ══ ⚠ WHAT WAS NOT KNOWN, AND WHAT I GOT WRONG FIRST ══
 *
 * I originally recorded this lead as *"5733 BP_MaterialEffect_Dismantle_C::SetMeshes warnings ... owned
 * by GameFeatures/SS_Mod"*. Two thirds of that was wrong and it is worth writing down:
 *
 *  - It is NOT a material-lookup failure. The `[BuildEffect] Failed to find remap material` errors I had
 *    bundled with it do not appear in this log at all.
 *  - `BP_MaterialEffect_Dismantle_C` is a VANILLA class name, and Structural Solutions is content-only
 *    with no `Source` and no modules — so it cannot be the C++ caller, though its buildables could well
 *    be what the effect is being run ON.
 *
 * **The caller is genuinely unknown.** `UFGMaterialEffectComponent`'s .cpp in the SML tree is an
 * autogenerated stub, so the call sites are invisible from here. That is what this probe is for.
 *
 * ══ HOW IT NAMES THE CALLER, AND WHY NOT A STACK WALK ══
 *
 * A module-level stack walk (the `FFPMStallSampler` technique) would name the DLL. That is the wrong
 * granularity: nearly every call arrives through Blueprint, so the answer would be "the engine" for all
 * of them.
 *
 * ★ The OWNING ACTOR'S CLASS PATH names it exactly and costs one string. A vanilla buildable reads
 * `/Script/FactoryGame.AFGBuildable...`; a modded one reads `/SS_Mod/...` or another mount point. The
 * mount point IS the mod. No stack walk, no access transformer, no module table.
 *
 * ══ IT IS AN OBSERVER AND NOTHING ELSE ══
 *
 * ⚠ IT NEVER CANCELS AND NEVER MUTATES. The call always falls through to vanilla, so the game behaves
 * exactly as it did without FPM. Fixing the ordering is a SEPARATE decision that cannot be made until
 * the caller is known — and guessing at a fix for an unknown caller is how this project's worst
 * regressions happened.
 *
 * ⚠ COST: the census does real work only until it saturates, then every call is one atomic increment.
 * This function is called in bursts of hundreds, so the saturated path is the one that matters and it is
 * deliberately trivial.
 *
 * ⚠ NON-VIRTUAL TARGET, so plain `SUBSCRIBE_METHOD` and not the `_VIRTUAL` form. `SetMeshes` carries no
 * `virtual` at `FGMaterialEffectComponent.h:68`, and `_VIRTUAL` on a non-virtual function resolves
 * through a member-pointer thunk that would not be what vanilla calls.
 *
 * ZERO RESIDUE: counters and names in memory. No cvar, no ini, nothing written to any object.
 * BOTH SIDES: `Side() == Any`. A dedicated server runs build effects too, and knowing whether the
 * server sees this as well is part of the question.
 */
class FFPMMaterialEffectProbe final : public IFPMFix
{
public:
	static FFPMMaterialEffectProbe& Get();

	virtual const TCHAR* Name() const override { return TEXT("material-effect-probe"); }

	/** The server runs build effects too, and whether it sees the same rejection is part of the finding. */
	virtual EFPMFixSide Side() const override { return EFPMFixSide::Any; }

	/**
	 * UnknownCause, and honestly so. The SYMPTOM is precise — a documented lifecycle contract violated
	 * 431 times — and the mechanism that violates it is exactly what is missing. This fix exists to
	 * produce that name, which is the diagnostic the enum demands of anything not `OriginNamed`.
	 */
	virtual EFPMOriginStatus OriginStatus() const override { return EFPMOriginStatus::UnknownCause; }

	virtual FPMDiag::EChannel Channel() const override { return FPMDiag::EChannel::MaterialEffect; }

	virtual void Arm() override;
	virtual void Disarm() override;

	/** `FPM.MaterialEffect.Report` — total calls, and the owner classes that made them. */
	static void LogReport(class FOutputDevice* Ar = nullptr);
};
